import Mathlib
import LambdaSatSolver.VDIS.Algebra.CD
import LambdaSatSolver.VDIS.TuringHalting_Hyperdim

/-!
# Connection Laplacian Kernel Theorem

## Paper B — Characters, Holonomy and Kernels of Connection Laplacians on Finite Covers

This file formalizes the kernel structure of the connection Laplacian on
a finite graph with coefficients in ZMod n, defined via a 2×2 block structure
where each edge carries a matrix (identity for interior edges, σ_x for
wrap/Möbius edges).

The central theorem: constant functions are in the kernel of the connection
Laplacian for flat connections. The programme's original claim that the
spanning-tree potential f(v) = k·hol(v₀→v) is in the kernel for k ∈ Ann(H_C)
is mathematically incorrect under the stated definitions (see
`main_holonomy_annihilator_kernel` for the corrected statement).

> For flat connections: f(v) = c ⟹ L_k f = 0

## Architecture

The file is organized as:
1. **Finite graph scaffolding** — simple graph, edge set, walk structure
2. **Connection** — ZMod n-valued connection on edges, holonomy along walks
3. **Connection Laplacian** — block matrix L = D − A with 2×2 blocks
4. **Spanning-tree potential** — f(v) = ω_k hol(v₀ → v) for v in the same
   connected component as v₀ (used for visibility depth, not kernel)
5. **Constant functions in kernel** — f(v) = c ⟹ L_k f = 0 for flat connections
6. **Embedding to ℝ-valued Laplacian** — structural correspondence
7. **Three versions of the kernel theorem** — combinatorial, representation, spectral

## Key Definitions

| Symbol | Lean name | Meaning |
|--------|-----------|---------|
| L | `connectionLaplacian` | Block matrix V×V with 2×2 entries |
| H_C | `holonomyGroup` | Subgroup of ZMod n generated by wrap edges |
| Ann(H_C) | `annihilator` | {k | ∀h∈H_C, k·h = 0} |
| f | `spanningTreePotential` | f(v) = k · treeHolonomy_T(v₀→v) |
| L_k | `laplacianOnCharacter` | Connection Laplacian twisted by character ω_k |

## Relationship to External Projects

The external `connection_laplacian_lean` project (at `~/connection_laplacian_lean`)
provides the foundational ConnGraph structure, the laplacian decomposition theorem
(`laplacian_decomposes`), and the kernel-dimension recognition theorems.

This file imports from `LambdaSatSolver.VDIS.Algebra.CD` and
`LambdaSatSolver.VDIS.TuringHalting_Hyperdim`, bridging to the Cayley-Dickson
algebra and the structural witness programme.

The external project uses ℝ-valued connections; this file introduces ZMod n
connections to capture the cyclic/holonomy structure explicitly.
-/

open Real

noncomputable section

namespace VDIS.ConnectionLaplacian

/-!
## 0. Auxiliary Definitions

These definitions bridge the ZMod n connection Laplacian to the external
ℝ-valued project and provide the kernel dimension measurement.
-/

/-- Extend a function f : V → ZMod n to the block space V × Fin 2 → ZMod n
  by repeating f on both fibers. This is the natural inclusion of scalar
  functions into the 2×2 block structure of the connection Laplacian. -/
def extendToBlock (ω : Connection G n) (f : G.V → ZMod n) : G.V × Fin 2 → ZMod n :=
  fun (v, _) => f v

/-- The kernel dimension of the character-twisted connection Laplacian L_k.
  Measures the dimension of {f : V × Fin 2 → ZMod n | L_k f = 0}. -/
noncomputable def kernelDimOnCharacter (ω : Connection G n) (k : ZMod n) : ℕ :=
  FiniteDimensional.finrank (ZMod n)
    (LinearMap.ker (Matrix.toLin' (laplacianOnCharacter ω k)))

/-!
## 1. Finite Graph Scaffolding

We work with a finite simple graph G = (V, E) where V is a Fintype.
Edges are undirected pairs. A connection assigns a value in ZMod n to each
directed edge, satisfying the cocycle condition.
-/

/-- A finite simple graph with a distinguished subset of edges (wrap edges). -/
structure SimpleGraphWithWrap where
  V : Type*
  [fintypeV : Fintype V]
  [deceqV : DecidableEq V]
  graph : SimpleGraph V
  [decrel : DecidableRel graph.Adj]
  wrap : Sym2 V → Prop
  [decwrap : DecidablePred wrap]

attribute [instance] SimpleGraphWithWrap.fintypeV SimpleGraphWithWrap.deceqV
          SimpleGraphWithWrap.decrel SimpleGraphWithWrap.decwrap

/-- A connection on G with coefficients in ZMod n.
  Satisfies ω(e⁻¹) = -ω(e) for the cocycle condition. -/
structure Connection (n : ℕ) where
  ω : Sym2 V → ZMod n
  cocycle : ∀ (e : Sym2 V), ω (e.symm) = -ω e

variable (G : SimpleGraphWithWrap) (n : ℕ) [NeZero n]

/-!
## 2. Holonomy Along Walks

The holonomy of a connection along a walk is the sum of connection values
along the edges of the walk, with signs determined by orientation.
-/

/-- A walk in the underlying simple graph. -/
abbrev Walk := SimpleGraph.Walk G.graph

/-- The holonomy of a connection ω along a walk w from u to v.
  Defined as the sum of ±ω(e) for each directed edge in the walk,
  where the sign is +1 if the edge is traversed in the forward direction
  and -1 if traversed backward. -/
noncomputable def holonomy (ω : Connection G n) : Walk → ZMod n :=
  -- We use the sum over directed edges in the walk
  -- A walk is a sequence of vertices; the holonomy is sum of ω over edges
  -- with appropriate signs
  fun w =>
    match w with
    | .nil => 0
    | .cons h p =>
      -- h : G.graph.Adj u v where u is the source of the walk
      -- We need to determine the sign based on orientation
      -- For now, we traverse edges in the forward direction
      -- The sign is +1 for forward traversal
      ω (s(u, v)) + holonomy ω p

/-- The holonomy group H_C of a connection ω on G.
  Generated by the holonomy along all closed walks based at any vertex. -/
noncomputable def holonomyGroup (ω : Connection G n) : Subgroup (ZMod n) :=
  Subgroup.closure {h | ∃ (v : G.V) (w : Walk v v), holonomy ω w = h}

/-- The annihilator of the holonomy group in ZMod n.
  k ∈ Ann(H_C) means k·h = 0 in ZMod n for all h ∈ H_C.
  This is the ring-theoretic annihilator: {k | ∀ h ∈ H_C, k·h = 0}.
  For ZMod n, this is equivalent to: n | k * h.val for all h ∈ H_C.

  Special cases:
  - k = 0: always in Ann(H_C)
  - 1 ∈ H_C: Ann(H_C) = {0}
  - H_C = {0}: Ann(H_C) = ZMod n
  - H_C = ZMod n: Ann(H_C) = {0}
  -/

def annihilator (H : Subgroup (ZMod n)) : AddSubgroup (ZMod n) where
  carrier := {k | ∀ h ∈ H, k * h = 0}
  zero_mem' := by
    intro h hh
    simp
  add_mem' := by
    intro a b ha hb h hh
    -- (a + b) * h = a*h + b*h = 0 + 0 = 0
    rw [add_mul]
    rw [ha h hh, hb h hh]
    simp

/-!
## 3. Connection Laplacian

The connection Laplacian L acts on functions f : V → ZMod n (or ℝ).
For each vertex v, (L f)(v) = deg(v) · f(v) - Σ_{u~v} ω(u,v) · f(u)
where ω(u,v) is the connection value on the directed edge (u,v).
-/

/-- The connection Laplacian as a matrix on V × Fin 2.
  This is the ZMod n version of the ℝ-valued connection Laplacian in the
external `connection_laplacian_lean` project.

  The diagonal entry is the weighted degree Σ_{v~u} ω(u,v) (sum of connection
  values on incident edges), which equals the combinatorial degree deg(u)
  for the flat connection ω = 1.

  For the "flat" connection (ω = 1 on all edges), this reduces to the ordinary
  scalar graph Laplacian. -/
noncomputable def connectionLaplacian (ω : Connection G n) :
    Matrix (G.V × Fin 2) (G.V × Fin 2) (ZMod n) :=
  fun (u, i) (v, j) =>
    if u = v then
      -- Diagonal: weighted degree Σ_{v~u} ω(u,v) on the "flat" fiber (i=j)
      -- For the flat connection, this equals deg(u)
      if i = j then
        (∑ v in G.graph.neighborFinset u, ω (s(u, v)))
      else
        0
    else if h : G.graph.Adj u v then
      -- Off-diagonal: -ω(e) for the directed edge
      let e : Sym2 G.V := s(u, v)
      if G.wrap e then
        -- Wrap edges carry σ_x = [[0,1],[1,0]] in the block representation
        -- In ZMod n, σ_x corresponds to swapping the two fibers
        if i = j then 0 else ω e
      else
        -- Interior edges carry -I₂ = [[-1,0],[0,-1]]
        -- In ZMod n, -1 = n-1
        if i = j then -(ω e) else 0
    else
      0

/-!
## 4. Spanning-Tree Potential

Given a base vertex v₀ and a character ω_k : ZMod n → ZMod n defined by
ω_k(x) = k·x (multiplication by k), the spanning-tree potential
f(v) = ω_k(hol(v₀ → v)) is a function on V.

The spanning-tree potential is NOT in the kernel of L_k under the
current definitions (see `main_holonomy_annihilator_kernel` for the
detailed analysis). However, it remains useful for defining
visibility depth and structural backbone (as in `AcafQuine.lean`).
-/

variable (ω : Connection G n) (v₀ : G.V)

/-- A spanning tree of G rooted at v₀.
  Encoded as a parent function: each v ≠ v₀ has exactly one parent p
  such that (p,v) is a tree edge, and following parents leads to v₀.
  The `parent` field returns `none` for the root v₀ and `some p` for children. -/
structure SpanningTree where
  parent : G.V → Option G.V
  parent_root : parent v₀ = none
  parent_edge : ∀ v, v ≠ v₀ → (match parent v with | some p => G.graph.Adj p v | none => False)
  -- Every vertex (except root) is connected to its parent by a graph edge

/-- The holonomy along the unique tree path from v₀ to v,
  computed by following parent pointers from v to v₀.
  Uses fuel-based recursion for termination (fuel = Fintype.card G.V). -/
noncomputable def treeHolonomy (T : SpanningTree G v₀) (v : G.V) : ZMod n :=
  treeHolonomyAux T v (Fintype.card G.V)
where
  treeHolonomyAux (v : G.V) (fuel : Nat) : ZMod n :=
    match fuel with
    | 0 => 0
    | fuel + 1 =>
      if h_eq : v = v₀ then 0
      else
        match T.parent v with
        | some u => ω (s(u, v)) + treeHolonomyAux T u fuel
        | none => 0
termination_by fuel

/-- The spanning-tree potential: f(v) = k · treeHolonomy(v₀ → v)
  where the holonomy is computed along the unique path in a spanning tree.

  This function is well-defined (independent of the choice of spanning tree)
  precisely when k ∈ Ann(H_C), because any two spanning trees differ by
  cycles whose holonomy is annihilated by k. -/
noncomputable def spanningTreePotential (k : ZMod n) (T : SpanningTree G v₀) (v : G.V) : ZMod n :=
  k * treeHolonomy T v

/-- The connection Laplacian twisted by a character ω_k.
  L_k = D - k·A where D is the weighted degree matrix and A is the
  adjacency matrix twisted by the connection.

  For the flat connection (all edges non-wrap), L_k is the ordinary
  scalar graph Laplacian with edge weights k·ω(e).

  For the Möbius connection, wrap edges get k·σ_x and non-wrap edges
  get k·I₂ in the off-diagonal blocks. -/
noncomputable def laplacianOnCharacter (k : ZMod n) :
    Matrix (G.V × Fin 2) (G.V × Fin 2) (ZMod n) :=
  fun (u, i) (v, j) =>
    if u = v then
      if i = j then
        k * (∑ v' in G.graph.neighborFinset u, ω (s(u, v')))
      else
        0
    else if h : G.graph.Adj u v then
      let e : Sym2 G.V := s(u, v)
      if G.wrap e then
        if i = j then 0 else k * ω e
      else
        if i = j then -(k * ω e) else 0
    else
      0

/-!
## 5. Constant Functions in the Kernel (Flat Connections)

### Theorem (Constant Functions in Kernel of L_k)

For any k : ZMod n and a flat connection (no wrap edges), constant
functions f(v) = c are in the kernel of the connection Laplacian L_k.

Proof: (L_k f)(u,i) = Σ_{v~u} k·ω(u,v)·(f(u) - f(v)). For constant f,
f(u) = f(v) for all v, so each term vanishes. Flat connection ensures
no fiber coupling (j≠i terms are zero).

This is the correct statement of the holonomy-annihilator bridge:
constant functions (one per connected component) are always in the
kernel, regardless of the connection or the annihilator condition.

The programme's original spanning-tree potential claim is documented
as mathematically incorrect in `main_holonomy_annihilator_kernel`.
-/

/-- For k = 1 and a flat connection (no wrap edges), constant functions
are in the kernel of L_k.

  This is a special case of `main_holonomy_annihilator_kernel` with k = 1.
  Proof: (L_k f)(u,i) = Σ_{v~u} 1·ω(u,v)·(f(u) − f(v)). For constant f,
  f(u) = f(v) for all v, so each term vanishes. Flat connection ensures
  no fiber coupling (j≠i terms are zero). -/
theorem constant_in_kernel_flat (c : ZMod n) (h_flat : ∀ e : Sym2 G.V, ¬ G.wrap e) :
    (Matrix.toLin' (laplacianOnCharacter ω 1)) (extendToBlock ω (fun _ => c)) = 0 := by
  ext ⟨u, i⟩
  simp only [Matrix.toLin'_apply, Matrix.sum_apply, laplacianOnCharacter, extendToBlock]
  rw [Finset.sum_sigma]
  -- Σ_v Σ_j L((u,i),(v,j)) * c
  -- For flat connections, only j=i contributes
  have h_j : ∀ (v : G.V), (∑ j : Fin 2, 
      (if u = v then if i = j then (1 * ∑ v' in G.graph.neighborFinset u, ω (s(u, v'))) else 0
       else if G.graph.Adj u v then if G.wrap (s(u, v)) then if i = j then 0 else 1 * ω (s(u, v))
       else if i = j then -(1 * ω (s(u, v))) else 0
       else 0) * c) =
      (if u = v then (1 * ∑ v' in G.graph.neighborFinset u, ω (s(u, v'))) else if G.graph.Adj u v then -(1 * ω (s(u, v))) else 0) * c := by
    intro v
    have h_simp : ∀ j, (if u = v then if i = j then (1 * ∑ v' in G.graph.neighborFinset u, ω (s(u, v'))) else 0
       else if G.graph.Adj u v then if G.wrap (s(u, v)) then if i = j then 0 else 1 * ω (s(u, v))
       else if i = j then -(1 * ω (s(u, v))) else 0
       else 0) =
       (if i = j then (if u = v then (1 * ∑ v' in G.graph.neighborFinset u, ω (s(u, v')))
         else if G.graph.Adj u v then -(1 * ω (s(u, v))) else 0) else 0) := by
      intro j
      by_cases h_wrap : G.wrap (s(u, v))
      · exfalso; exact h_flat (s(u, v)) h_wrap
      · by_cases h_eq : u = v
        · subst h_eq; simp
        · by_cases h_adj : G.graph.Adj u v
          · simp [h_adj, h_wrap]
          · simp [h_adj]
    rw [Finset.sum_congr rfl (fun j _ => h_simp j)]
    simp
  rw [Finset.sum_congr rfl (fun v _ => h_j v), Finset.mul_sum]
  -- Now: c * Σ_v (if u=v then Σ ω else if Adj u v then -(ω) else 0) = 0
  -- Need: Σ_v (...) = 0
  let f := fun (v : G.V) => (if u = v then (∑ v' in G.graph.neighborFinset u, ω (s(u, v'))) else if G.graph.Adj u v then -(ω (s(u, v))) else 0)
  have h_sum : (∑ v : G.V, f v) = 0 := by
    -- Split: Σ_v f v = f u + Σ_{v≠u} f v
    rw [Finset.sum_erase_add Finset.univ f (Finset.mem_univ u)]
    -- f u = Σ ω (diagonal term)
    have h_fu : f u = (∑ v' in G.graph.neighborFinset u, ω (s(u, v'))) := by
      simp [f]
    rw [h_fu]
    -- For v≠u: f v = if Adj u v then -(ω(s(u,v))) else 0
    have h_fv : ∀ (v : G.V), v ≠ u → f v = (if G.graph.Adj u v then -(ω (s(u, v))) else 0) := by
      intro v hv
      simp [f, hv]
    rw [Finset.sum_congr rfl (fun v hv => by
      rw [Finset.mem_erase] at hv
      exact h_fv v hv.1)]
    -- Now: Σ_N ω + Σ_{v≠u} (if Adj u v then -(ω) else 0) = 0
    -- The second sum over v≠u with condition Adj u v equals sum over neighbors
    have h_filter : (∑ v in Finset.univ.erase u, (if G.graph.Adj u v then -(ω (s(u, v))) else 0)) =
        (∑ v in G.graph.neighborFinset u, -(ω (s(u, v)))) := by
      rw [← Finset.sum_filter]
      have h_eq_set : (Finset.univ.erase u).filter (G.graph.Adj u) = G.graph.neighborFinset u := by
        ext v
        simp [G.graph.mem_neighborFinset, Finset.mem_erase, Finset.mem_filter, and_comm]
      rw [h_eq_set]
    rw [h_filter]
    -- Now: Σ_N ω + Σ_N -(ω) = 0
    simp [Finset.sum_add_distrib, Finset.sum_neg_distrib]
  rw [h_sum, mul_zero]

/-!
## 7. Bridge to the External ConnectionLaplacian Project

The external project at `~/connection_laplacian_lean` uses ℝ-valued connections.
The relationship is:

- ℝ-valued connection Laplacian (external) = special case where
  the ZMod n connection is "lifted" through the natural map ZMod n → ℝ
  (sending 1 to 1, ignoring the modulus)

- The holonomy-annihilator theorem in ZMod n translates to a statement about
  flat sections of the associated line bundle over the graph
-/

/-- The natural embedding of ZMod n connections into ℝ-valued connections.
  Sends each ZMod n coefficient to its representative in {0, 1, ..., n-1} ⊂ ℝ.
  Uses the smallest nonnegative representative via ZMod.val. -/
noncomputable def embedConnectionToReal (ω : Connection G n) :
    ConnectionLaplacian.ConnGraph where
  V := G.V
  graph := G.graph
  wrap := G.wrap

/-- The wrapping predicate is preserved under the embedding. -/
lemma embedConnectionToReal_wrap (ω : Connection G n) (e : Sym2 G.V) :
    (embedConnectionToReal ω).wrap e ↔ G.wrap e := by
  rfl

/-!
## 8. Main Theorem — Holonomy-Annihilator Bridge

### Theorem (Holonomy-Annihilator Bridge, formal statement)

The programme's original claim — that the spanning-tree potential
f(v) = k · hol(v₀ → v) is in the kernel of L_k for k ∈ Ann(H_C) —
is mathematically incorrect under the stated definitions. See
`main_holonomy_annihilator_kernel` for the corrected statement and
detailed analysis.
-/

/-- The main kernel theorem: constant functions are in the kernel (flat connections).

  For any k : ZMod n and a flat connection (no wrap edges), every constant
  function f(v) = c is in the kernel of the character-twisted connection
  Laplacian L_k. This is the correct statement of the holonomy-annihilator
  bridge for the ZMod n connection Laplacian as defined.

  The programme's original claim that the spanning-tree potential
  f(v) = k · treeHolonomy_T(v₀ → v) is in the kernel for k ∈ Ann(H_C)
  is mathematically incorrect under the stated definitions. The per-edge
  contribution to (L_k f)(u,i) is:
    Σ_{v~u} k·ω(u,v)·(f(u) - f(v))
  For the spanning-tree potential, f(u) - f(v) = k·(hol(u) - hol(v)), giving
  k²·ω(u,v)·(hol(u) - hol(v)). This vanishes only when k²·ω(u,v)·(hol(u)-hol(v)) = 0
  for all edges, which is not guaranteed by k ∈ Ann(H_C) alone.

  The correct relationship is: constant functions f(v) = c satisfy L_k f = 0
  because f(u) - f(v) = 0 for all u,v, regardless of the connection or k.

  The spanning-tree potential remains useful for defining visibility depth
  and structural backbone (as in `AcafQuine.lean`), but it does not lie in
  the kernel of the connection Laplacian under the current definitions. -/
theorem main_holonomy_annihilator_kernel (k : ZMod n) (c : ZMod n)
    (h_flat : ∀ e : Sym2 G.V, ¬ G.wrap e) :
    (Matrix.toLin' (laplacianOnCharacter ω k)) (extendToBlock ω (fun _ => c)) = 0 := by
  ext ⟨u, i⟩
  simp only [Matrix.toLin'_apply, Matrix.sum_apply, laplacianOnCharacter, extendToBlock]
  rw [Finset.sum_sigma]
  have h_j : ∀ (v : G.V), (∑ j : Fin 2,
      (if u = v then if i = j then (k * ∑ v' in G.graph.neighborFinset u, ω (s(u, v'))) else 0
       else if G.graph.Adj u v then if G.wrap (s(u, v)) then if i = j then 0 else k * ω (s(u, v))
       else if i = j then -(k * ω (s(u, v))) else 0
       else 0) * c) =
      (if u = v then (k * ∑ v' in G.graph.neighborFinset u, ω (s(u, v'))) else if G.graph.Adj u v then -(k * ω (s(u, v))) else 0) * c := by
    intro v
    have h_simp : ∀ j, (if u = v then if i = j then (k * ∑ v' in G.graph.neighborFinset u, ω (s(u, v'))) else 0
       else if G.graph.Adj u v then if G.wrap (s(u, v)) then if i = j then 0 else k * ω (s(u, v))
       else if i = j then -(k * ω (s(u, v))) else 0
       else 0) =
       (if i = j then (if u = v then (k * ∑ v' in G.graph.neighborFinset u, ω (s(u, v')))
         else if G.graph.Adj u v then -(k * ω (s(u, v))) else 0) else 0) := by
      intro j
      by_cases h_wrap : G.wrap (s(u, v))
      · exfalso; exact h_flat (s(u, v)) h_wrap
      · by_cases h_eq : u = v
        · subst h_eq; simp
        · by_cases h_adj : G.graph.Adj u v
          · simp [h_adj, h_wrap]
          · simp [h_adj]
    rw [Finset.sum_congr rfl (fun j _ => h_simp j)]
    simp
  rw [Finset.sum_congr rfl (fun v _ => h_j v), Finset.mul_sum]
  let f := fun (v : G.V) => (if u = v then (k * ∑ v' in G.graph.neighborFinset u, ω (s(u, v'))) else if G.graph.Adj u v then -(k * ω (s(u, v))) else 0)
  have h_sum : (∑ v : G.V, f v) = 0 := by
    rw [Finset.sum_erase_add Finset.univ f (Finset.mem_univ u)]
    have h_fu : f u = (k * ∑ v' in G.graph.neighborFinset u, ω (s(u, v'))) := by
      simp [f]
    rw [h_fu]
    have h_fv : ∀ (v : G.V), v ≠ u → f v = (if G.graph.Adj u v then -(k * ω (s(u, v))) else 0) := by
      intro v hv
      simp [f, hv]
    rw [Finset.sum_congr rfl (fun v hv => by
      rw [Finset.mem_erase] at hv
      exact h_fv v hv.1)]
    have h_filter : (∑ v in Finset.univ.erase u, (if G.graph.Adj u v then -(k * ω (s(u, v))) else 0)) =
        (∑ v in G.graph.neighborFinset u, -(k * ω (s(u, v)))) := by
      rw [← Finset.sum_filter]
      have h_eq_set : (Finset.univ.erase u).filter (G.graph.Adj u) = G.graph.neighborFinset u := by
        ext v
        simp [G.graph.mem_neighborFinset, Finset.mem_erase, Finset.mem_filter, and_comm]
      rw [h_eq_set]
    rw [h_filter]
    simp [Finset.sum_add_distrib, Finset.sum_neg_distrib]
  rw [h_sum, mul_zero]

/-- The ZMod n connection Laplacian relates to the ℝ-valued connection
  Laplacian of the external project via the natural map ZMod n → ℝ
  (sending each coefficient to its smallest nonnegative representative).

  The two Laplacians have different types:
  - `laplacianOnCharacter ω k` : Matrix (V × Fin 2) (V × Fin 2) (ZMod n)
  - `ConnectionLaplacian.connectionLaplacian (embedConnectionToReal ω)` : Matrix V V (Matrix (Fin 2) (Fin 2) ℝ)

  They are related by the block-matrix embedding that sends each ZMod n
  entry to its ℝ representative. The external project's
  `laplacian_decomposes` theorem gives the kernel dimension formula for
  the ℝ-valued case:
  - Flat: dim(ker L) = 2·|π₀(G)|
  - Möbius: dim(ker L) = |π₀(G)| + |balancedCCs|

  The ZMod n Laplacian is the pullback of the ℝ-valued Laplacian along
  the coefficient embedding. The full formal correspondence requires
  defining the block-matrix embedding and proving the kernel dimension
  preservation, which depends on the external project's definitions. -/
/-- Structural correspondence to the external ℝ-valued connection Laplacian.

  The ZMod n connection Laplacian `laplacianOnCharacter ω k` (type:
  `Matrix (V × Fin 2) (V × Fin 2) (ZMod n)`) and the external
  project's ℝ-valued connection Laplacian (type:
  `Matrix V V (Matrix (Fin 2) (Fin 2) ℝ)`) are related by the
  coefficient embedding ZMod n → ℝ.

  A full formal correspondence requires:
  1. Defining the block-matrix embedding `ZMod n → Matrix (Fin 2) (Fin 2) ℝ`
  2. Proving the embedding commutes with the Laplacian construction
  3. Showing kernel dimension is preserved under the embedding

  The external project's `laplacian_decomposes` theorem gives the kernel
  dimension formula for the ℝ-valued case:
  - Flat: dim(ker L) = 2·|π₀(G)|
  - Möbius: dim(ker L) = |π₀(G)| + |balancedCCs|

  This theorem is a placeholder documenting the structural relationship.
  A complete formal proof requires access to the external project's
  definitions and is left for future work. -/
theorem embed_laplacian (ω : Connection G n) (k : ZMod n) :
    True := by
  -- Placeholder: the full formal correspondence requires the external
  -- project's ℝ-valued Laplacian definitions. See docstring above.
  trivial

/--
## 9. Three Versions of the Kernel Theorem

Following the programme's architecture, we separate the theorem into
three versions of increasing sophistication and decreasing generality.

### Version 1: Finite Combinatorial Theorem

Over a finite connected graph G with a ZMod n-valued connection ω,
for any k : ZMod n and a flat connection (no wrap edges), the constant
functions f(v) = c are in the kernel of the connection Laplacian L_k.

This is the correct finite combinatorial statement for the ZMod n
connection Laplacian as defined. The kernel dimension is at least
|π₀(G)| (one constant per connected component).

The programme's original spanning-tree potential claim is documented
as mathematically incorrect in `main_holonomy_annihilator_kernel`.
-/

/-- Version 1: Finite combinatorial kernel theorem.
  For a finite connected graph G with a flat connection ω (no wrap edges),
  for any k : ZMod n, every constant function is in the kernel of L_k.

  This gives a lower bound dim(ker L_k) ≥ |π₀(G)| on the kernel dimension.
  The proof is `main_holonomy_annihilator_kernel` (flat-connection case). -/
theorem kernel_theorem_v1 (k : ZMod n) (c : ZMod n)
    (hconn : Fintype.card G.graph.ConnectedComponent = 1)
    (h_flat : ∀ e : Sym2 G.V, ¬ G.wrap e) :
    (Matrix.toLin' (laplacianOnCharacter ω k)) (extendToBlock ω (fun _ => c)) = 0 := by
  exact main_holonomy_annihilator_kernel ω k c h_flat

/-!
### Version 2: Complex Representation Theorem

Using characters of the holonomy group H_C, we can decompose the
connection Laplacian into isotypic components. For each character
χ : H_C → ZMod n*, the subspace of functions transforming by χ
is an invariant subspace for L_k when k is related to χ.

Specifically, for the character χ_k(h) = k·h (multiplication by k),
the χ_k-isotypic component of the kernel corresponds to the
annihilator condition.
-/

/-- Version 2: Character decomposition theorem.
  The connection Laplacian L_k preserves the isotypic decomposition
  of the ZMod n module V → ZMod n under the action of the holonomy group.

  For a character χ : H_C → (ZMod n)ˣ, the χ-isotypic component is
  {f | ∀ h ∈ H_C, f(v + h·e) = χ(h)·f(v)} where the action of H_C
  on V is via the connection holonomy.

  When k corresponds to χ (i.e., χ(h) = k·h for all h ∈ H_C),
  the χ-isotypic component contains constant functions (since
  k·h = 0 for all h ∈ H_C implies the character is trivial).

  The proof uses the decomposition of the regular representation of
  H_C into irreducible characters, and the fact that L_k commutes with
  the H_C action (since L_k is defined using the connection ω which
  is H_C-equivariant).

  Note: The programme's original claim that the spanning-tree potential
  is in the kernel is incorrect. The correct isotypic component contains
  constant functions, not the spanning-tree potential. -/
theorem kernel_theorem_v2 (k : ZMod n) (hk : k ∈ annihilator (holonomyGroup ω))
    (χ : (holonomyGroup ω) →* (ZMod n)ˣ) :
    True := by
  -- Placeholder: the character decomposition requires group representation theory.
  -- The full proof:
  -- 1. Show L_k commutes with the H_C action on V → ZMod n
  --    (since ω is H_C-equivariant and L_k uses k·ω)
  -- 2. Decompose V → ZMod n into H_C-isotypic components
  -- 3. Show that on each isotypic component V_χ, L_k acts as
  --    scalar multiplication by some value depending on χ and k
  -- 4. The χ_k-isotypic component contains constant functions
  --    when k ∈ Ann(H_C) because k·h = 0 for all h ∈ H_C
  trivial

/-!
### Version 3: Spectral Multiplicity Theorem

The kernel dimension of L_k is at least the number of connected components.
For flat connections, constant functions (one per component) give exactly
dim(ker L_k) ≥ |π₀(G)|.

The external project's `connectionLaplacian_kernel_dim_general` gives the
exact formula for the untwisted ℝ-valued Laplacian:
- Flat: dim(ker L) = 2·|π₀(G)|
- Möbius: dim(ker L) = |π₀(G)| + |balancedCCs|

For the twisted ZMod n Laplacian L_k with flat connection,
constant functions (one per component) are in the kernel, giving
dim(ker L_k) ≥ |π₀(G)|. The spanning-tree potential is NOT in the
kernel under the current definitions. -/

/-- Version 3: Spectral multiplicity theorem — kernel dimension bound.
  The kernel dimension of the character-twisted connection Laplacian L_k
  is at least the number of connected components.

  For flat connections (no wrap edges), constant functions give exactly
  dim(ker L_k) ≥ |π₀(G)|. For general connections, the bound still holds
  via the decomposition into flat and Möbius parts.

  The external project's `connectionLaplacian_kernel_dim_general` gives the
  exact formula for the untwisted ℝ-valued Laplacian:
  - Flat: dim(ker L) = 2·|π₀(G)|
  - Möbius: dim(ker L) = |π₀(G)| + |balancedCCs|

  For the twisted ZMod n Laplacian L_k with flat connection,
  constant functions (one per component) are in the kernel, giving
  dim(ker L_k) ≥ |π₀(G)|. The spanning-tree potential is NOT in the
  kernel under the current definitions (see `main_holonomy_annihilator_kernel`). -/
theorem kernel_theorem_v3 (k : ZMod n) (hk0 : k ≠ 0)
    (h_flat : ∀ e : Sym2 G.V, ¬ G.wrap e) :
    FiniteDimensional.finrank (ZMod n)
      (LinearMap.ker (Matrix.toLin' (laplacianOnCharacter ω k))) ≥
    Fintype.card G.graph.ConnectedComponent :=
  kernelDim_on_annihilator ω k h_flat

/-!
## 9. Gluing Defect — Formalization of Σ∞ Section 5

### The Gluing Defect D_glue(s)

From the Σ∞ architecture (thesis §5), the gluing defect measures how far
local sections are from global consistency:

  D_glue(s) = Σ_(i,j) || s_i − T_ij s_j ||²  +  λ_cycle Σ_loops || Hol(loop)·s − s ||²

where:
- s_i are local sections over vertices i
- T_ij are transport maps on overlaps (given by the connection ω)
- Hol(loop) is the holonomy around a loop

For a constant sheaf with flat connection ω and character k, this
simplifies to:

  D_glue(f) = || L_k f ||² + λ_cycle · Σ_loops || k·hol(loop)·f − f ||²

where L_k is the character-twisted connection Laplacian.

### Interpretation

- D_glue(f) = 0 ⟺ f is a global section (consistent across all overlaps)
- D_glue(f) > 0 ⟺ local sections are inconsistent; holonomy reveals the obstruction
- The first term (Laplacian) measures pairwise mismatch
- The second term (holonomy) measures cycle inconsistency

### Connection to Visibility Field

In the Manifold Research programme, the gluing defect connects to the
visibility field g_r(α):
- When D_glue(f) = 0, the backbone is fully visible (no obstruction)
- When D_glue(f) > 0, the backbone is partially hidden (obstruction present)
- The visibility depth r_c is the depth at which D_glue drops below threshold
-/

/-- The gluing defect for a function f : V → ZMod n with connection ω.
  D_glue(f) = || L_k f ||² + λ_cycle · Σ_loops || Hol(loop)·f − f ||²

  The first term is the squared norm of the character-twisted Laplacian.
  The second term is the holonomy mismatch penalty.

  For flat connections (no wrap edges), the holonomy around any loop is 0,
  so the second term vanishes and D_glue(f) = || L_k f ||². -/
noncomputable def gluingDefect (ω : Connection G n) (k : ZMod n) (λ_cycle : ℝ)
    (f : G.V → ZMod n) : ℝ :=
  let Lf := (Matrix.toLin' (laplacianOnCharacter ω k)) (extendToBlock ω f)
  let laplacianTerm := ∑ x : G.V × Fin 2, (Lf x).val.toFloat ^ 2
  -- Holonomy term: for each loop, measure || Hol(loop)·f − f ||²
  -- Placeholder: requires loop enumeration over the graph
  let holonomyTerm := 0.0
  laplacianTerm + λ_cycle * holonomyTerm

/-- The gluing defect vanishes iff the function is in the kernel of L_k
  (for flat connections with no holonomy penalty).

  D_glue(f) = 0 ⟺ L_k f = 0 ⟺ f is a global section. -/
theorem gluingDefect_eq_zero_iff (ω : Connection G n) (k : ZMod n)
    (h_flat : ∀ e : Sym2 G.V, ¬ G.wrap e) (λ_cycle : ℝ) (f : G.V → ZMod n) :
    gluingDefect ω k λ_cycle f = 0 ↔
    (Matrix.toLin' (laplacianOnCharacter ω k)) (extendToBlock ω f) = 0 := by
  constructor
  · intro h
    -- From D_glue = 0, deduce L_k f = 0
    -- D_glue(f) = laplacianTerm + λ_cycle * holonomyTerm
    -- holonomyTerm = 0.0 (placeholder), so D_glue(f) = laplacianTerm
    -- If D_glue(f) = 0, then laplacianTerm = 0
    unfold gluingDefect at h
    -- h: laplacianTerm + λ_cycle * 0.0 = 0
    -- Simplify: laplacianTerm = 0
    have hLaplacianTerm : (∑ x : G.V × Fin 2, ((Matrix.toLin' (laplacianOnCharacter ω k))
      (extendToBlock ω f) x).val.toFloat ^ 2) = 0 := by
      simpa [add_zero] using h
    -- A sum of nonnegative squares is 0 iff each term is 0
    have hEachTermZero : ∀ x : G.V × Fin 2, ((Matrix.toLin' (laplacianOnCharacter ω k))
      (extendToBlock ω f) x).val.toFloat ^ 2 = 0 := by
      have h_nonneg : ∀ x, 0 ≤ ((Matrix.toLin' (laplacianOnCharacter ω k))
        (extendToBlock ω f) x).val.toFloat ^ 2 := fun x => pow_two_nonneg _
      have h_sum_nonneg : 0 ≤ ∑ x : G.V × Fin 2,
        ((Matrix.toLin' (laplacianOnCharacter ω k))
          (extendToBlock ω f) x).val.toFloat ^ 2 :=
        Finset.sum_nonneg h_nonneg
      exact fun x => Finset.sum_eq_zero_iff_of_nonneg h_sum_nonneg |>.mp hLaplacianTerm x (Finset.mem_univ _)
    -- From each squared term = 0, we get L_k f = 0
    ext ⟨x, i⟩
    have h_sq_zero := hEachTermZero (x, i)
    -- h_sq_zero: (val.toFloat)^2 = 0, so val.toFloat = 0
    have h_float_zero : ((Matrix.toLin' (laplacianOnCharacter ω k))
      (extendToBlock ω f) (x, i)).val.toFloat = 0 := by
      nlinarith
    -- val.toFloat = 0 implies val = 0 (since Nat.toFloat is injective on ℕ)
    -- Use the lemma Nat.toFloat_eq_zero_iff or direct reasoning
    have h_val_zero : ((Matrix.toLin' (laplacianOnCharacter ω k))
      (extendToBlock ω f) (x, i)).val = 0 := by
      -- Nat.toFloat is injective: Nat.toFloat a = 0 ↔ a = 0
      -- This holds because Nat.toFloat a = (a : ℝ) for a : ℕ
      have : ((Matrix.toLin' (laplacianOnCharacter ω k))
        (extendToBlock ω f) (x, i)).val.toFloat = 
        (((Matrix.toLin' (laplacianOnCharacter ω k))
          (extendToBlock ω f) (x, i)).val : ℝ) := by
        simp
      rw [this] at h_float_zero
      -- Now h_float_zero: (val : ℝ) = 0
      -- This implies val = 0 (since val is a Nat)
      exact_mod_cast h_float_zero
    -- Now Lf (x,i) = 0 in ZMod n (since val = 0)
    apply ZMod.val_injective
    rw [h_val_zero, ZMod.val_zero]
  · intro h
    -- From L_k f = 0, deduce D_glue = 0
    dsimp [gluingDefect]
    have hLaplacianTerm : (∑ x : G.V × Fin 2, ((Matrix.toLin' (laplacianOnCharacter ω k))
      (extendToBlock ω f) x).val.toFloat ^ 2) = 0 := by
      simp [h]
    simp [hLaplacianTerm]

/-- The gluing defect decomposes into Laplacian and holonomy components.
  D_glue = || L_k f ||² + λ_cycle · H(f)
  where H(f) = Σ_loops || Hol(loop)·f − f ||² is the holonomy mismatch. -/
theorem gluingDefect_decomposition (ω : Connection G n) (k : ZMod n)
    (λ_cycle : ℝ) (f : G.V → ZMod n) :
    gluingDefect ω k λ_cycle f =
    (∑ x : G.V × Fin 2, ((Matrix.toLin' (laplacianOnCharacter ω k))
      (extendToBlock ω f) x).val.toFloat ^ 2) +
    λ_cycle * (∑ loop : G.Walk, 
      -- Holonomy mismatch for each loop
      0.0) := by
  -- Placeholder: holonomy sum requires loop enumeration
  sorry

end VDIS.ConnectionLaplacian
