"""Lie/symmetry-channel probe of the Nullstellensatz obstruction (the operator's
"manipulate the channels to chase the lifting, Lie algebra as telos" thread).

The rank-deficiency operator M_d commutes with the formula's automorphism group
Gamma, so Gamma's orbits/irreps are literally the "channels" and the certificate
can be chased channel by channel. Over R this is standard symmetry-adapted SOS
block-diagonalization (Gatermann-Parrilo), generated by Gamma's Lie algebra.

This script tests the GF(2) shadow on PHP(3->2), whose automorphism group is
S_3 (pigeons) x S_2 (holes). Verdict (reproducible):

  the char-2 orbit-symmetrization operator SUM_{g in Gamma} g acts on any
  Gamma-invariant vector as multiplication by |Gamma|; since 2 | |Gamma| = 12
  this is 0, so it ANNIHILATES the invariant subspace -- and the target `1`
  lives in that subspace. The symmetric channel therefore provably cannot
  reach 1 (it stalls), while the true NS degree is 4. The Lie/symmetry-channel
  reduction is a real-field object; its clean GF(2) image is char-2 obstructed.

Run: python -m docs.ladder.scripts.symmetry_channel_ns
"""
from itertools import permutations

from backend.complexity.invariants import (
    _clause_violation_poly, _poly_mul, _deg, _maxdeg,
    _reduce_into_basis, _in_gf2_span, nullstellensatz_degree)
from backend.eval.generators import pigeonhole


def var_index(p, h):
    """PHP variable index x(p,h) for 3 pigeons, 2 holes (1-indexed 1..6)."""
    return (p - 1) * 2 + h


def perm_bit(mask, sigma, tau):
    """Act on a monomial bitmask by (pigeon perm sigma, hole perm tau)."""
    out = 0
    for p in range(1, 4):
        for h in range(1, 3):
            i = var_index(p, h) - 1
            if mask >> i & 1:
                j = var_index(sigma[p - 1], tau[h - 1]) - 1
                out |= (1 << j)
    return out


def main(dmax=6):
    cnf, _ = pigeonhole(3)
    n = cnf.num_vars
    print(f"PHP(3->2): n={n} vars, {len(cnf.clauses)} clauses; "
          f"brute NS degree = {nullstellensatz_degree(cnf, dmax=dmax)}")

    group = [(s, t) for s in permutations([1, 2, 3])
             for t in permutations([1, 2])]
    print(f"|Gamma| = {len(group)}  (even -> char-2 symmetrization collapses "
          f"invariants)")

    def symmetrize(poly):
        acc = set()
        for s, t in group:
            for m in poly:
                acc ^= {perm_bit(m, s, t)}
        return acc

    vcs = [_clause_violation_poly(c) for c in cnf.clauses]
    monos = [m for m in range(1 << n) if _deg(m) <= dmax]

    print("--- symmetric-channel (orbit-symmetrized) NS degree over GF(2) ---")
    result = None
    for d in range(0, dmax + 1):
        basis = {}
        for vc in vcs:
            for m in monos:
                if _deg(m) > d:
                    continue
                g = _poly_mul({m}, vc)
                if _maxdeg(g) > d:
                    continue
                sg = symmetrize(g)
                if sg and _maxdeg(sg) <= d:
                    _reduce_into_basis(basis, sg)
        reachable = _in_gf2_span(basis, {0})
        print(f"  d={d}: symmetric-channel basis rows={len(basis):3d}  "
              f"1-reachable={reachable}")
        if reachable and result is None:
            result = d
    print(f"symmetric-channel NS degree = {result}   (brute-force truth = 4)")
    print("=> char-2 obstruction confirmed: the Lie/symmetry channel is a "
          "real-field object.")


if __name__ == "__main__":
    main()
