"""S3.5 frozen per-family curvature lookup (Correction 2: offline sweep,
winner frozen, NO online kappa adaptation in v1).

Generated by docs/vdis/scripts/phase2_curvature_bandit.py on the quick +
medium suites (93 instances), full VDIS config (dim=32, beta=0.1,
lambda_tau=lambda_chi=0.1, seed=0), conflict cap 50000, winner per
(algebra, family) by (fewest capped runs, then fewest total decisions).
Values pasted verbatim from the script's output; per-kappa decision
totals kept as comments so the margins are visible.

Tie caveat: on families the solver finishes by unit propagation alone or
near-alone ('ladder': 0 decisions everywhere; 'xor-chain': 26 everywhere)
every kappa ties and the recorded "winner" is just the first arm in
sweep order (-0.25) - it carries no information and should not be read
as a preference.
"""

KAPPA_TABLE = {
    ("C", "graph-coloring"): -0.25,        # -2: 109, -1: 109, -0.5: 103, -0.25: 97
    ("C", "ladder"): -0.25,                # all 0 (tie - see caveat)
    ("C", "mutilated-chessboard"): -0.5,   # -2: 110, -1: 97, -0.5: 97, -0.25: 111
    ("C", "pigeonhole"): -2.0,             # -2: 14923, -1: 19135, -0.5: 20669, -0.25: 38597
    ("C", "random-3sat"): -0.25,           # -2: 7173, -1: 7585, -0.5: 7880, -0.25: 6342
    ("C", "random-4sat"): -0.25,           # -2: 8029, -1: 8885, -0.5: 8020, -0.25: 7876
    ("C", "xor-chain"): -0.25,             # all 26 (tie - see caveat)
    ("H", "graph-coloring"): -1.0,         # -2: 101, -1: 101, -0.5: 102, -0.25: 103
    ("H", "ladder"): -0.25,                # all 0 (tie - see caveat)
    ("H", "mutilated-chessboard"): -0.5,   # -2: 79, -1: 69, -0.5: 68, -0.25: 89
    ("H", "pigeonhole"): -0.5,             # -2: 20045, -1: 18255, -0.5: 18229, -0.25: 18720
    ("H", "random-3sat"): -1.0,            # -2: 7867, -1: 6907, -0.5: 7368, -0.25: 9508
    ("H", "random-4sat"): -2.0,            # -2: 7278, -1: 9101, -0.5: 7733, -0.25: 11161
    ("H", "xor-chain"): -0.25,             # all 26 (tie - see caveat)
}

DEFAULT_KAPPA = -1.0  # families not in the table (P4's global baseline)


def kappa_for(algebra: str, family: str) -> float:
    return KAPPA_TABLE.get((algebra, family), DEFAULT_KAPPA)
